# Generated by Django 5.2.3 on 2025-06-28 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anggota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Buku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("penulis", models.CharField(max_length=100)),
                ("stok", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TransaksiPeminjaman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_pinjam", models.DateField(auto_now_add=True)),
                ("tanggal_kembali", models.DateField(blank=True, null=True)),
                ("dikembalikan", models.BooleanField(default=False)),
                (
                    "anggota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peminjaman.anggota",
                    ),
                ),
                (
                    "buku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peminjaman.buku",
                    ),
                ),
            ],
        ),
    ]
